CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers
(
	id int NOT NULL AUTO_INCREMENT,
	burger_name varchar(25) NOT NULL,
	devoured BOOLEAN NOT NULL DEFAULT 0,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
)